use_frameworks!

platform :ios, '13.0'

target 'WhisperDiarization_Example' do
  pod 'WhisperDiarization', :path => '../'

  target 'WhisperDiarization_Tests' do
    inherit! :search_paths

    
  end
end
